//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przychodnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class jednostka_leku
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public jednostka_leku()
        {
            this.dawka_leku = new HashSet<dawka_leku>();
        }
    
        public int id_jednostki { get; set; }
        public string nazwa_jednostki { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dawka_leku> dawka_leku { get; set; }
    }
}
