//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przychodnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class karta_pacjenta
    {
        public int id_karty { get; set; }
        public Nullable<int> id_pacjenta { get; set; }
        public Nullable<int> wykonane_uslugi { get; set; }
        public string kod_choroby { get; set; }
        public Nullable<int> id_leku { get; set; }
        public Nullable<int> lekarz_prowadzacy { get; set; }
        public string diagnoza { get; set; }
    
        public virtual choroby choroby { get; set; }
        public virtual lek lek { get; set; }
        public virtual lekarz lekarz { get; set; }
        public virtual pacjent pacjent { get; set; }
        public virtual uslugi uslugi { get; set; }
    }
}
