//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przychodnia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class clinicEntities : DbContext
    {
        public clinicEntities()
            : base("name=clinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<choroby> choroby { get; set; }
        public virtual DbSet<dawka_leku> dawka_leku { get; set; }
        public virtual DbSet<jednostka_leku> jednostka_leku { get; set; }
        public virtual DbSet<karta_pacjenta> karta_pacjenta { get; set; }
        public virtual DbSet<lek> lek { get; set; }
        public virtual DbSet<lekarz> lekarz { get; set; }
        public virtual DbSet<pacjent> pacjent { get; set; }
        public virtual DbSet<rejestracja> rejestracja { get; set; }
        public virtual DbSet<specjalizacja> specjalizacja { get; set; }
        public virtual DbSet<uslugi> uslugi { get; set; }
    }
}
