//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przychodnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class rejestracja
    {
        public int id_rejestracji { get; set; }
        public Nullable<int> id_pacjenta { get; set; }
        public Nullable<int> id_lekarza { get; set; }
        public System.DateTime data_rejestracji { get; set; }
        public System.TimeSpan godzina { get; set; }
    
        public virtual lekarz lekarz { get; set; }
        public virtual pacjent pacjent { get; set; }
    }
}
